//Clothes, vests and backpacks

//Common, everyday uniforms
commonUniforms = [
	"U_BG_Guerilla_6_1",
	"U_BG_Guerilla_1_1",
	"U_BG_Guerilla_2_1",
	"U_BG_Guerilla_2_2",
	"U_BG_Guerilla_2_3",
	"U_BG_Guerilla_3_1",
	"U_BG_leader",
	"U_C_HunterBody_grn",
	"U_C_Journalist",
	"U_C_Rangemaster",
	"U_B_survival_uniform",
	"U_B_WorkerCoveralls",
	"U_C_Poloshirt_blue",
	"U_C_Poloshirt_burgundy",
	"U_C_Poloshirt_redwhite",
	"U_C_Poloshirt_salmon",
	"U_C_Poloshirt_tricolor",
	"U_C_rvg_hood_bandit",
	"rvg_bandit",
	"rvg_camo",
	"rvg_diamond",
	"rvg_goodie_bandit",
	"rvg_goodie_grey",
	"rvg_goodie_blue",
	"rvg_goodie_red",
	"rvg_goodie_kabeiroi",
	"rvg_retro_bandit",
	"rvg_retro_green",
	"rvg_retro_grey",
	"rvg_retro_kabeiroi",
	"rvg_retro_red",
	"rvg_shirt_bandit",
	"rvg_shirt_check",
	"rvg_shirt_kabeiroi",
	"rvg_shirt_stripe",
	"U_C_WorkerCoverallsBandit",
	"U_C_WorkerCoverallsBlack",
	"U_C_WorkerCoverallsCamo",
	"rvg_survivor",
	"U_I_G_Story_Protagonist_F"
];

//Military uniforms (with ghilies and such)
rareUniforms = [
	"UK3CB_BAF_U_Smock_MTP",
	"UK3CB_BAF_U_RolledUniform_MTP",
	"UK3CB_BAF_U_JumperUniform_MTP",
	"UK3CB_BAF_U_CombatUniform_MTP",
	"UK3CB_BAF_U_CombatUniform_MTP_TShirt",
	"rhs_uniform_cu_ucp",
	"rhs_uniform_acu_ucp",
	"rhs_uniform_cu_ocp",
	"rhs_uniform_acu_ocp",
	"rhs_uniform_bdu_erdl",
	"rhs_uniform_FROG01_d",
	"rhs_uniform_FROG01_wd",
	"rhs_uniform_g3_mc",
	"rhs_uniform_flora_patchless",
	"rhs_uniform_m88_patchless",
	"rhs_uniform_mflora_patchless",
	"rhs_uniform_gorka_1_b",
	"U_B_GhillieSuit",
	"U_B_FullGhillie_sard",
	"rhs_uniform_cu_ucp"
];

//Common, every day headgears
commonHeadgears = [
	"H_Bandanna_gry",
	"H_Bandanna_khk",
	"H_Booniehat_khk",
	"H_Cap_oli",
	"H_Cap_blk",
	"H_BandMask_blk",
	"H_Watchcap_blk",
	"H_Cap_grn",
	"H_Cap_tan",
	"H_MilCap_blue",
	"H_MilCap_ocamo",
	"H_MilCap_mcamo",
	"H_MilCap_dgtl",
	"H_Cap_headphones",
	"rhs_fieldcap",
	"rhs_fieldcap_digi",
	"rhs_fieldcap_izlom",
	"rhs_fieldcap_khk",
	"rhs_fieldcap_vsr",
	"rhsusf_brownman_cap",
	"rhsusf_patrolcap_ocp",
	"rhsusf_patrolcap_ucp",
	"H_BandCap_rvg",
	"rhs_beanie_green",
	"rhs_beanie",
	"H_Booniehat_mcamo",
	"H_Booniehat_oli",
	"H_Booniehat_tan",
	"H_Booniehat_dgtl",
	"rhs_Booniehat_digi",
	"rhs_Booniehat_flora",
	"rhs_Booniehat_m81",
	"rhs_Booniehat_ocp",
	"rhs_Booniehat_ucp",
	"rhs_booniehat2_marpatd",
	"rhs_booniehat2_marpatwd",
	"H_Beret_blk",
	"H_Beret_02",
	"H_Beret_Colonel",
	"rhs_beret_mp2",
	"rhs_beret_mp1",
	"rhs_beret_mvd",
	"rhs_beret_vdv1",
	"rhs_beret_vdv2",
	"rhs_beret_vdv3",
	"rhs_beret_milp",
	"H_RacingHelmet_1_black_F",
	"H_RacingHelmet_1_blue_F",
	"H_RacingHelmet_2_F",
	"H_RacingHelmet_1_F",
	"H_RacingHelmet_1_green_F",
	"H_RacingHelmet_1_red_F",
	"H_RacingHelmet_3_F",
	"H_RacingHelmet_4_F",
	"H_RacingHelmet_1_white_F",
	"H_RacingHelmet_1_yellow_F",
	"H_ShemagOpen_tan",
	"H_ShemagOpen_khk",
	"H_Shemag_olive"
];

//Military headgears
rareHeadgear = [
	"rhsusf_ach_bare",
	"rhsusf_opscore_fg",
	"rhsusf_mich_bare",
	"UK3CB_BAF_H_Mk7_Camo_A",
	"rhs_6b28_green",
	"rhs_6b26_green",
	"rhs_6b27m_green",
	"rhs_6b27m_green",
	"rhs_altyn_visordown",
	"rhs_ssh68"
];

//Vests with small capacity. Include ones that privide good protection but no space too
commonVests = [
	"V_Chestrig_khk",
	"V_Harness0_brn",
	"V_Rangemaster_belt",
	"V_BandollierV_khk",
	"rhs_6b23",
	"rhs_6sh92",
	"rhs_6b43",
	"rhs_6sh46",
	"rhs_vest_commander",
	"rhs_vydra_3m",
	"rhsusf_plateframe_sapi",
	"rhsusf_spc",
	"V_TacVest_khk",
	"UK3CB_BAF_V_PLCE_Webbing_OLI"
];

rareVests = [
	"V_PlateCarrierL_CTGR",
	"V_PlateCarrierH_CTGR",
	"V_PlateCarrierIAGL_oli",
	"rhs_6b23_Flora_6sh92_vog",
	"rhs_6b23_digi_6sh92_vog",
	"rhs_6b23_6sh116_vog_flora",
	"rhsusf_iotv_ocp_Rifleman",
	"rhsusf_iotv_ocp_Rifleman",
	"rhsusf_mbav_light",
	"rhsusf_spc_rifleman",
	"rhsusf_spcs_ocp_rifleman",
	"UK3CB_BAF_V_Osprey",
	"UK3CB_BAF_V_Osprey_DDPM1"
];

commonBackpack = [
	"ace_gunbag",
	"ace_TacticalLadder_Pack",
	"B_AssaultPack_khk",
	"B_FieldPack_khk",
	"rhsusf_assault_eagleaiii_ocp",
	"rhsusf_falconii_mc",
	"rhs_sidor",
	"rhs_rpg_empty",
	"rhs_medic_bag"
];

rareBackpack = [
	"B_Carryall_oli",
	"B_Kitbag_mcamo",
	"B_TacticalPack_mcamo",
	"UK3CB_BAF_B_Bergen_MTP_Rifleman_XL_A"
];